// Copyright 2025, Luminant. All Rights Reserved.

#include "LuminantExpansionEditorModule.h"
#include "Modules/ModuleManager.h"
#include "Kismet2/KismetEditorUtilities.h"
#include "AbilitySystem/LE_AbilityObject.h"

DEFINE_LOG_CATEGORY(LogMyEditor);

#define LOCTEXT_NAMESPACE "FLuminantExpansionEditorModule"

void FLuminantExpansionEditorModule::StartupModule()
{
    UE_LOG(LogMyEditor, Warning, TEXT("MyEditor: Module Started"));

    // Register our auto-generated event nodes
    PrepareAutoGeneratedDefaultEvents();
}

void FLuminantExpansionEditorModule::ShutdownModule()
{
    UE_LOG(LogMyEditor, Warning, TEXT("MyEditor: Module Ended"));

    // Cleanup all auto-generated events registered by this module
    FKismetEditorUtilities::UnregisterAutoBlueprintNodeCreation(this);
}

void FLuminantExpansionEditorModule::PrepareAutoGeneratedDefaultEvents()
{
    // Register default events for your UObject class
    RegisterDefaultEvent(this, ULE_AbilityObject, ActivateAbility);
}

#undef LOCTEXT_NAMESPACE

// Module name must match your editor module name in .uplugin
IMPLEMENT_MODULE(FLuminantExpansionEditorModule, LuminantExpansionEditor)
