// Copyright 2025, Luminant. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "Modules/ModuleManager.h"
#include "Kismet2/KismetEditorUtilities.h"

DECLARE_LOG_CATEGORY_EXTERN(LogMyEditor, All, All);

// Macro outside class
#define RegisterDefaultEvent(ModuleInstance, ClassType, FuncName) \
    FKismetEditorUtilities::RegisterAutoGeneratedDefaultEvent(ModuleInstance, ClassType::StaticClass(), GET_FUNCTION_NAME_CHECKED(ClassType, FuncName))

class FLuminantExpansionEditorModule : public IModuleInterface
{
public:
    virtual void StartupModule() override;
    virtual void ShutdownModule() override;

private:
    void PrepareAutoGeneratedDefaultEvents();
};